// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAySpQr8IxP1tqUjUr0BqqgNhLUa8WMtnI',
    appId: '1:737750224396:web:69b7e21ff4ca8c514ba829',
    messagingSenderId: '737750224396',
    projectId: 'news-8635c',
    authDomain: 'news-8635c.firebaseapp.com',
    storageBucket: 'news-8635c.firebasestorage.app',
    measurementId: 'G-5WVRSCCNE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYyCeVs5nIVybRJ4cdbfLIjOfyQ3buKY4',
    appId: '1:737750224396:android:24ea1b3c37e3cbcc4ba829',
    messagingSenderId: '737750224396',
    projectId: 'news-8635c',
    storageBucket: 'news-8635c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlUOdTMyjxR-vbSAhZcpIVa0Pg4hc0twA',
    appId: '1:737750224396:ios:0539a947c1504b0e4ba829',
    messagingSenderId: '737750224396',
    projectId: 'news-8635c',
    storageBucket: 'news-8635c.firebasestorage.app',
    iosBundleId: 'com.example.newsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlUOdTMyjxR-vbSAhZcpIVa0Pg4hc0twA',
    appId: '1:737750224396:ios:0539a947c1504b0e4ba829',
    messagingSenderId: '737750224396',
    projectId: 'news-8635c',
    storageBucket: 'news-8635c.firebasestorage.app',
    iosBundleId: 'com.example.newsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAySpQr8IxP1tqUjUr0BqqgNhLUa8WMtnI',
    appId: '1:737750224396:web:a70e7caa6a948a944ba829',
    messagingSenderId: '737750224396',
    projectId: 'news-8635c',
    authDomain: 'news-8635c.firebaseapp.com',
    storageBucket: 'news-8635c.firebasestorage.app',
    measurementId: 'G-7MSK41EEKX',
  );
}
